services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: data-portal-https-portal
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: |
        cbioportal.wehi-rcp.cloud.edu.au -> http://cbioportal-container:8080
        omero.wehi-rcp.cloud.edu.au -> http://omero-web:80
      STAGE: production
    volumes:
      - https-portal-data:/var/lib/https-portal
    networks:
      - cbio-net
    restart: unless-stopped

volumes:
  https-portal-data:

networks:
  cbio-net:
    external: true
    name: cbioportal-docker-compose_cbio-net
